{{- if .Values.nodeSliceController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whereabouts.fullname" . }}-controller
  {{- include "whereabouts.namespace" . | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "whereabouts.fullname" . }}-controller
  template:
    metadata:
      labels:
        app: {{ include "whereabouts.fullname" . }}-controller
    spec:
      containers:
        - command:
            - /node-slice-controller
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: whereabouts
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cnibin
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /cron-schedule
              name: cron-scheduler-configmap
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-6kd6k
              readOnly: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ include "whereabouts.serviceAccountName" . }}
      serviceAccountName: {{ include "whereabouts.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /opt/cni/bin
            type: ""
          name: cnibin
        - hostPath:
            path: /etc/cni/net.d
            type: ""
          name: cni-net-dir
        - configMap:
            defaultMode: 484
            items:
              - key: cron-expression
                path: config
            name: {{ include "whereabouts.fullname" . }}-config
          name: cron-scheduler-configmap
        - name: kube-api-access-6kd6k
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
{{- end}}
