name: "Push helm chart on release"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

on:
  push:
    tags:
      - v*
jobs:
  package-and-push-helm-chart:
    runs-on: ubuntu-22.04
    steps:
      - name: install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: update chart
        env:
          GITHUB_TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
        run: make chart-prepare-release
    
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deployment/whereabouts-chart/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: push chart
      #   env:
      #     GITHUB_TAG: ${{ github.ref_name }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REPO_OWNER: ${{ github.repository_owner }}
      #   run: make chart-push-release
